name: 'Internal Testing Uploader'
description: 'Upload aab/apk to Internal Testing Track (initernal, alpha, beta etc) on Play Console'
inputs:
  serviceAccountJsonPlainText:
    description: 'The service account json plain text private key file to authorize the upload request'
    required: true 
  packageName:
    description: 'Package name of the application'
    required: true
  apkFilePath:
    description: '.apk file path'
    required: false
  aabFilePath:
    description: '.aab file path'
    required: false
  track:
    description: 'Testing track name: internal, alpha etc'
    required: false
outputs:
  versionCode:
    description: 'Version code of the uploaded artifact'
  sha1:
    description: 'A sha1 hash of the artifact, encoded as a hex string and matching the output of the sha1sum command.'
  sha256:
    description: 'A sha256 hash of the artifact, encoded as a hex string and matching the output of the sha256sum command.'
runs:
  using: 'node12'
  main: 'dist/index/index.js'
  post: 'dist/cleanup/index.js'
branding:
  icon: 'upload-cloud'  
  color: 'green'
